apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - service.yml
  - cronjob.yml

configMapGenerator:
  - name: ui-components-config
    literals:
      - AWS_REGION=eu-west-1

commonLabels:
  app: ui-components
