apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
  - deployment.yml
resources:
  - ../../base
  - external-secret.yml
  - ingress.yml

configMapGenerator:
  - name: ui-components-config
    behavior: merge
    literals:
      - ENVIRONMENT=staging
