apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
  - deployment.yml

resources:
  - ../../base
  - external-secret.yml
  - ingress.yml
  - pdb.yml

configMapGenerator:
  - name: ui-components-config
    behavior: merge
    literals:
      - ASPNETCORE_ENVIRONMENT=Production
      - ENVIRONMENT=production
      - DOMAIN=quicklookup.com
      - BACKEND_URL=https://api.quicklookup.com
      - FRONTEND_URL=https://app.quicklookup.com
      - S3_BUCKET=files.quicklookup.com
